export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const SIGN_UP_USER = "SIGN_UP_USER";

export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSE_TYPE = 'FETCH_COURSE_TYPE';
export const CHANGE_PAGE_COURSES = 'CHANGE_PAGE_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const REGISTER_A_COURSE = 'REGISTER_A_COURSE';
export const DELETE_USER_FROM_COURSE = 'DELETE_USER_FROM_COURSE';

export const FETCH_USERS = "FETCH_USERS";
export const ADD_USER = "ADD_USER";
export const GET_WAITING_STUDENTS = 'GET_WAITING_STUDENTS';
export const GET_CURRENT_STUDENTS = 'GET_CURRENT_STUDENTS';
export const GET_WAITING_COURSES = 'GET_WAITING_COURSES';
export const GET_CURRENT_COURSES = 'GET_CURRENT_COURSES';

export const FETCH_USER_INFO = "FETCH_USER_INFO";
