export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_CREDENTIALS = 'FETCH_CREDENTIALS';

export const CHANGE_PAGE_COURSES = 'CHANGE_PAGE_COURSES';

export const ADD_COURSE = 'ADD_COURSE';
